### ISSUE TITLE
about cuda memory

### ISSUE THREAD

**Issue by bugcat9** [LeonHLJ/RSKP#1]
Thans for your work.
I run the code and get the error:
`RuntimeError: CUDA error: invalid configuration argument`
It seems to be a gpu memory problem, how much memory you are using?

**Comment by LeonHLJ** [comment]
We use about 1G GPU memory during training. If your GPU memory is enough,
please check your configuration, e.g., PyTorch version, etc.

ning ***@***.***> 於 2022年3月17日週四 下午8:47寫道：

**Comment by LeonHLJ** [comment]
> Thans for your work. I run the code and get the error: `RuntimeError: CUDA error: invalid configuration argument` It seems to be a gpu memory problem, how much memory you are using?


We use about 1.2G GPU memory during training. If your GPU memory is enough, please check your configuration, e.g., PyTorch version, etc.

**Comment by bugcat9** [comment]
en,thank you

**Comment by kailigo** [comment]
Meet the same problem, wondering how was it solved. Looks not because of the memory limit (my machine has 24G). Thanks.

**Comment by bugcat9** [comment]
i change the Pytorch version and the code run successfully

**Comment by LeonHLJ** [comment]
> Meet the same problem, wondering how was it solved. Looks not because of the memory limit (my machine has 24G). Thanks.

Please ensure that your environment is consistent with the recommended environment, especially the Pytorch version. Thanks.
