### ISSUE TITLE
sorry I can't reproduce the result of the RSKP, the best of the map is only 43.7

### ISSUE THREAD

**Issue by Value-Jack** [LeonHLJ/RSKP#10]
Classification map 96.154649
Detection map @ 0.100000 = 69.094885
Detection map @ 0.200000 = 63.238989
Detection map @ 0.300000 = 54.506203
Detection map @ 0.400000 = 45.565674
Detection map @ 0.500000 = 36.865112
Detection map @ 0.600000 = 24.011744
Detection map @ 0.700000 = 12.755108
average map = 43.719674

and I download your model offered, and only get the result about 44.7

**Comment by LeonHLJ** [comment]
I can reproduce the results after loading the provided model, what version of PyTorch do you use? Or did you change any lines of the code?
