### ISSUE TITLE
how to solve the warning "WARNING batched routines are designed for small sizes. It might be better to use the    Native/Hybrid classical routines if you want good performance."

### ISSUE THREAD

**Issue by Value-Jack** [LeonHLJ/RSKP#11]

**Comment by kelesy923** [comment]
Have you solved the problem?

**Comment by LeonHLJ** [comment]
This warning is because we take inverse on a large matrix, it would not affect the final performance. If you want to get rid of this warning, maybe try some other operations of matrix inversion.
