### ISSUE TITLE
Problem about train on ActivitiNet

### ISSUE THREAD

**Issue by Lcode119** [LeonHLJ/RSKP#12]
Hello author, I train RSKP on ActivitiNet, without any modification, and the map obtained has always been 0, is there a problem in what link?
![image](https://github.com/LeonHLJ/RSKP/assets/74463230/01908d83-d455-4e84-96e9-77f16309f5d7)

**Comment by LeonHLJ** [comment]
Thank you for your interest in our research. As it is commonly understood, ActivityNet videos typically contain a single action per video, with action durations often spanning the entire video. Consequently, training and testing on ActivityNet differs from the methods used for THUMOS. For detailed training and testing strategies applicable to ActivityNet, you can refer to [ACMNet](https://github.com/ispc-lab/ACM-Net).

> Hello author, I train RSKP on ActivitiNet, without any modification, and the map obtained has always been 0, is there a problem in what link? ![image](https://private-user-images.githubusercontent.com/74463230/311415010-01908d83-d455-4e84-96e9-77f16309f5d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMDI1ODMsIm5iZiI6MTcxMDAwMjI4MywicGF0aCI6Ii83NDQ2MzIzMC8zMTE0MTUwMTAtMDE5MDhkODMtZDQ1NS00ZTg0LTk2ZTktNzdmMTYzMDlmNWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE2MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2RkNzFiNmQ0ZTE1OWEwNTYxMDJlZTQ0YjgzMjRkNTgyZmI0ZDY5MGYxM2VjNDhmNjQ2NjY0N2RkYjI1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YQPmXUns2A5EKYVCQAJNFdrnmSLfCaevT-YtyWnyDVM)

**Comment by Lcode119** [comment]
Thank you for your reply,I will try it again.
