### ISSUE TITLE
Question About Paper

### ISSUE THREAD

**Issue by LimGeunTaekk** [LeonHLJ/RSKP#5]
Hi thanks for your good work!

I have a question about the paper.

![캡처](https://user-images.githubusercontent.com/70448161/185337013-209ae25b-6381-4299-a9d7-ddcb6ae3be2d.PNG)

I can't understand how Z_t's dimension is **t by n** not **l by n**

Should t be considered the number of video snippets equal to l?

Thank you

**Comment by LeonHLJ** [comment]
> Hi thanks for your good work!
> 
> I have a question about the paper.
> 
> ![캡처](https://user-images.githubusercontent.com/70448161/185337013-209ae25b-6381-4299-a9d7-ddcb6ae3be2d.PNG)
> 
> I can't understand how Z_t's dimension is **t by n** not **l by n**
> 
> Should t be considered the number of video snippets equal to l?
> 
> Thank you

Sorry, it's a typo, which should be **l by n** actually, l denotes the number of snippets in the video. If you have any further questions, pls feel free to contact me.

**Comment by LimGeunTaekk** [comment]
Thank you now it is clear.

Once again, thank you for your good research.
