### ISSUE TITLE
Question About Memory Bank

### ISSUE THREAD

**Issue by LimGeunTaekk** [LeonHLJ/RSKP#7]
Hi thanks for your good work!

I have a question about the source code.

https://github.com/LeonHLJ/RSKP/blob/2a156e824f7afc1359bd1ec1976b31c867cbe5c9/processor.py#L140

The idxs value continues to return to zero only not the real video label index.

<img width="213" alt="스크린샷 2022-09-16 오후 5 18 54" src="https://user-images.githubusercontent.com/70448161/190591598-abfd2f69-bfdf-4ac4-abee-801ca8bf6419.png">

This is because the code refers to the 0th return value of **np.where**

I wonder if this is intended for now.

Thank You.

**Comment by LeonHLJ** [comment]
> Hi thanks for your good work!
> 
> I have a question about the source code.
> 
> https://github.com/LeonHLJ/RSKP/blob/2a156e824f7afc1359bd1ec1976b31c867cbe5c9/processor.py#L140
> 
> The idxs value continues to return to zero only not the real video label index.
> 
> <img alt="스크린샷 2022-09-16 오후 5 18 54" width="213" src="https://user-images.githubusercontent.com/70448161/190591598-abfd2f69-bfdf-4ac4-abee-801ca8bf6419.png">
> 
> This is because the code refers to the 0th return value of **np.where**
> 
> I wonder if this is intended for now.
> 
> Thank You.

Thanks for your valuable question. This should be an error caused by uploading the wrong version, this line should be
 `idxs = np.where(np_labels==1)[1].tolist()`.

**Comment by LimGeunTaekk** [comment]
Thank you! now it is clear
