### ISSUE TITLE
Features of THUMOS14

### ISSUE THREAD

**Issue by Six-walnuts-Lu** [LeonHLJ/RSKP#9]
Thank you very much for providing the features. But this link can't be clicked now.
![1667010390384](https://user-images.githubusercontent.com/105764651/198778324-424fdefb-0598-41bb-987a-c7537e23b627.jpg)

Can you save the features to Baidu online disk and share them, or send a copy to my email（ L18103662029@163.com ）。 Thank you very much and wish you a happy life.

**Comment by LeonHLJ** [comment]
> Thank you very much for providing the features. But this link can't be clicked now. ![1667010390384](https://user-images.githubusercontent.com/105764651/198778324-424fdefb-0598-41bb-987a-c7537e23b627.jpg)
> 
> Can you save the features to Baidu online disk and share them, or send a copy to my email（ [L18103662029@163.com](mailto:L18103662029@163.com) ）。 Thank you very much and wish you a happy life.

I think it could be a system error, I can open the link. Maybe you should try again or try the link in [W-TALC](https://github.com/sujoyp/wtalc-pytorch).

**Comment by Six-walnuts-Lu** [comment]
Well, thank you very much. I'm trying

**Comment by LiangXu123** [comment]
根据你的描述及报错，你的朋友似乎是在分享此文件时创建了组织内人员的分享链接。如果是这样的话，你必须用你朋友组织内的学校或工作账号登录查看文件。所以首先请联系你的朋友请他确认他创建了[此文档]
I suppose some settings are wrong while you are sharing your documents.

**Comment by LeonHLJ** [comment]
> 根据你的描述及报错，你的朋友似乎是在分享此文件时创建了组织内人员的分享链接。如果是这样的话，你必须用你朋友组织内的学校或工作账号登录查看文件。所以首先请联系你的朋友请他确认他创建了[此文档] I suppose some settings are wrong while you are sharing your documents.

We use the features provided by [W-TALC](https://github.com/sujoyp/wtalc-pytorch), I think they have changed the shared link, leading to this problem. I updated the link, you can open it now.
